name: flutter_bloc_login
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Authentication Domain
  authentication_repository:
    path: packages/authentication_repository
  # User Domain
  user_repository:
    path: packages/user_repository
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
